name: routes_and_the_rest
description: A Flutter animation project showcasing routing animations.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_villains: ^1.2.1
  google_fonts: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.1.2

flutter:

  uses-material-design: true
  assets:
    - assets/images/